/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StressTestLazyImport = createFileRoute('/stress-test')()
const PhysicsLazyImport = createFileRoute('/physics')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StressTestLazyRoute = StressTestLazyImport.update({
  path: '/stress-test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stress-test.lazy').then((d) => d.Route))

const PhysicsLazyRoute = PhysicsLazyImport.update({
  path: '/physics',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/physics.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/physics': {
      preLoaderRoute: typeof PhysicsLazyImport
      parentRoute: typeof rootRoute
    }
    '/stress-test': {
      preLoaderRoute: typeof StressTestLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PhysicsLazyRoute,
  StressTestLazyRoute,
])

/* prettier-ignore-end */
